format = """
[](#9A2795)\
$python\
$username\
[](bg:#8837CA fg:#9A2795)\
$directory\
[](fg:#8837CA bg:#C2329D)\
$time\
[ ](fg:#C2329D)\
$character
"""

command_timeout = 5000
# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A2795"
style_root = "bg:#9A2795"
format = '[$user ]($style)'

[python]
style = "bg:#9A2795"
format = '[(\($virtualenv\) )]($style)'

[directory]
style = "bg:#8837CA"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#C2329D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#C2329D"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C2329D"
format = '[ $time ]($style)'
